services:
  mysql:
    image: mysql:8.0
    container_name: mysql-persistant
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config_local:/config_local
    ports:
      - "3306:3306"

volumes:
  mysql_data:
